# Generated by Django 5.1.4 on 2025-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_project_alter_taskdetails_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='tasks.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(related_name='tasks', to='tasks.employee'),
        ),
    ]
