# Generated by Django 5.1.4 on 2025-01-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_project_members_alter_task_assign_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='members',
            new_name='assign_to',
        ),
    ]
