# Generated by Django 5.1.4 on 2025-01-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_members_project_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
